### ISSUE TITLE
Android navigation

### ISSUE THREAD

**Issue by xzoom117** [xzoom117/E-Office#5]
@uta17 
Ta, website kamuteh kalo dilihat dari hp navigasinya ngebug kan?
kayak...
<p align="left">
<img src="https://i.ibb.co/mBS1QPz/Record-2021-02-05-09-08-49-326.gif" width="30%"/>
</p>

<br>Menurutku yang salah itu ada di cssnya
<b>[styleHome.css (line 215)]</b>

``` css
nav ul{
        position: absolute;
        right: 0;
        top: 0;
        height: 105.5vh;
        justify-content: space-evenly;
        flex-direction: column;
        align-items: center;
        background: linear-gradient(to left, rgb(93, 146, 226), rgb(170, 203, 255));
        z-index: 2;
        transform: translateX(100%);
        margin-top: 90px;
        transition: all 1s;
        opacity: 1;
    }
```

position harusnya `fixed`, opacity `0`, terus ditambah `width: 0%;`<br>
jadi si ccs `nav ul` teh navigasi versi mobile sebelum diklik (jadi belom muncul gening), sedangkan `nav ul.slide` teh navigasi mobile yang pas diklik.
