### ISSUE TITLE
Transform value

### ISSUE THREAD

**Issue by xzoom117** [xzoom117/E-Office#6]
@DollllllllllllChan Chan webmu teh kalo dilihat dari hp itu tabrak tabrakan kan..

<img src="https://i.ibb.co/y0WfJwf/2021-02-07-10-04-04-Window.png" alt="Issue" border="0">

Itutueh karena box box diatasnya enggak bener bener hilang, jadi kayak ada penghalang gitu gening, jadi transformnya kurang bener kalo layarnya terlalu panjang.<br>Jadi cara benerinnya teh..

# pengumuman.html

<details>
<summary>Click me</summary>

(line 57)
``` css
.TwoNdTugas .box{
	padding: 0px;
	border: 1px solid blue ;
  	margin: 0px;
	opacity: 0;
	transform: translateY(-50%);
	transform: translateX(-500%);
}
```
Border ganti ke `0px`, terus tambahin `font-size: 0%;`
<hr>

(line 65)
``` css
.TwoNdTugas .TwoNdBox{
	transform: translateY(-60%);
}
```
Transformnya ganti ke `-30%`

<hr>

(line 68)
``` css
.TwoNdTugas .ExtendBox{
	transform: translateX(-500%);
}
```

Tambahin...
``` css
font-size: 0%;
border: 0px;
padding: 0px;
margin: 0%;
```

<hr>

(line 71)
``` css
.TwoNdTugas .MaxBox{
	padding: 0px;
	border: 0px solid blue ;
  	margin: 0px;
	opacity: 0;
	transform: translateX(-500%);
}
```
(line 97)

``` css
.ExtendTugas .box{
	padding: 0px;
	border: 0px solid cadetblue ;
  	margin: 0px;
	opacity: 0;
	transform: translateY(-50%);
	transform: translateX(-500%);
}
```

(line 105)
``` css
.ExtendTugas .TwoNdBox{
	padding: 0px;
	border: 0px solid cadetblue ;
  	margin: 0px;
	opacity: 0;
	transform: translateY(-50%);
	transform: translateX(-500%);
}
```
(line 116)
``` css
.ExtendTugas .MaxBox{
	padding: 0px;
	border: 0px solid cadetblue ;
  	margin: 0px;
	opacity: 0;
	transform: translateX(-500%);
}
```
(line 142)
``` css
.MaxTugas .box{
	padding: 0px;
	border: 0px solid cadetblue ;
  	margin: 0px;
	opacity: 0;
	transform: translateY(-50%);
	transform: translateX(-500%);
}
```
(line 150)
``` css
.MaxTugas .TwoNdBox{
		padding: 0px;
		border: 0px solid cadetblue ;
  		margin: 0px;
		opacity: 0;
		transform: translateY(-50%);
		transform: translateX(-500%);
}
```
(line 158)
``` css
.MaxTugas .ExtendBox{
	padding: 0px;
	border: 0px solid cadetblue ;
  	margin: 0px;
	opacity: 0;
	transform: translateY(-50%);
	transform: translateX(-500%);
}
```
Tambahin `font-size: 0%;`

<hr>

(line 79)
``` css
.TwoNdTugas .TwoNdBox2{
  	border: 5px solid blue ;
  	padding: 10.8%;
  	margin: 20px;
	opacity: 1;
	font-size: 200%;
	transform: translateY(-68px);
}
```
(line 88)
``` css
.TwoNdTugas .BorderTwo{
	width: 98%;
	opacity: 1;
	transform: translateY(-68px);
	transition: all 1s;
	transition-delay: 0.5s;
}
```
Transformnya ganti ke `-38px`

<hr>

(line 113)
``` css
.ExtendTugas .ExtendBox{
	transform: translateY(-115%);
}
```
Transform ganti ke `-50%`

<hr>

(line 124)

``` css
.ExtendTugas .ExtendBox2{
  	border: 5px solid blue ;
  	padding: 10.8%;
  	margin: 20px;
	opacity: 1;
	font-size: 200%;
	transform: translateY(-125px);
}
```
(line 133)
``` css
.ExtendTugas .BorderExtend{
		width: 98%;
		opacity: 1;
		transform: translateY(-125px);
		transition: all 1s;
		transition-delay: 0.5s;
	}
```
Transform ganti `-60px`

<hr>

(line 166)

``` css
.MaxTugas .MaxBox{
	transform: translateY(-150%);
}
```
Transformnya kasih `-50%`

<hr>

(line 170)

``` css
.MaxTugas .MaxBox2{
  	border: 5px solid blue ;
  	padding: 10.5%;
  	margin: 20px;
	opacity: 1;
	font-size: 200%;
	transform: translateY(-170px);
}
```
Transform kasih `-70%`

<hr>

(line 179)

``` css
.MaxTugas .BorderMax{
	width: 98%;
	opacity: 1;
	transform: translateY(-165px);
	transition: all 1s;
	transition-delay: 0.5s;
}
```
Transform `-65px`
</details>

# style-Pengumuman.css

<details>
<summary>Click me</summary>

(line 65)
``` css
.TwoNdBox{
	-webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
    -khtml-user-select: none; /* Konqueror HTML */
    -moz-user-select: none; /* Old versions of Firefox */
    -ms-user-select: none; /* Internet Explorer/Edge */
    user-select: none; /* Non-prefixed version, currently supported by Chrome, Edge, Opera and Firefox */
	text-align: center;
	border: 0px solid cadetblue ;
	padding: 0px;
	margin: 0%;
	background-color:rgba(23, 87, 184, 0.884);
	font-size: 200%;
	color: white;
	font-family:monospace;
	opacity: 0;
	transform: translateY(-50%);
}
```

(line 94)

``` css
.ExtendBox{
	-webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
    -khtml-user-select: none; /* Konqueror HTML */
    -moz-user-select: none; /* Old versions of Firefox */
    -ms-user-select: none; /* Internet Explorer/Edge */
    user-select: none; /* Non-prefixed version, currently supported by Chrome, Edge, Opera and Firefox */
	text-align: center;
	border: 0px solid cadetblue ;
	padding: 0px;
	margin: 0%;
	background-color:rgba(23, 87, 184, 0.884);
	font-size: 200%;
	color: white;
	font-family: monospace;
	opacity: 0;
	transform: translateY(-70%);
}
```

(line 125)
``` css
.MaxBox{
	-webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
    -khtml-user-select: none; /* Konqueror HTML */
    -moz-user-select: none; /* Old versions of Firefox */
    -ms-user-select: none; /* Internet Explorer/Edge */
    user-select: none; /* Non-prefixed version, currently supported by Chrome, Edge, Opera and Firefox */
	text-align: center;
	border: 0px solid cadetblue ;
	padding: 0px;
	margin: 0%;
	background-color:rgba(23, 87, 184, 0.884);
	font-size: 200%;
	color: white;
	font-family: monospace;
	opacity: 0;
	transform: translateY(-90%);
}
```
Kasih `transform: translateX(-100%);`

<hr>

(line 162)
``` css
.BorderTwo{
	width:0%;
	opacity: 0;
	margin-left:auto;
	margin-right: auto;
	transition: all 1s;
	transform: translateY(-60px);
}
```
Transform ganti `-30px`

<hr>

(line 170)

``` css
.BorderExtend{
	width:0%;
	opacity: 0;
	margin-left:auto;
	margin-right: auto;
	transition: all 1s;
	transform: translateY(-115px);
}
```
Transform `-50px`

<hr>

(line 178)
``` css
.BorderMax{
	width:0%;
	opacity: 0;
	margin-left:auto;
	margin-right: auto;
	transition: all 1s;
	transform: translateY(-155px);
}
```
Transform `-55px`

</details>

<p align="center""><b>Ganbatte!!! 👀 👍 </b></p>
<img align="center" width="100%" src="https://media.giphy.com/media/kTSWqCuzUUELu/source.gif" alt="Semangat" border="0">
<br>
Kalau masih agak nabrak. coba ganti ganti aja sendiri, atau comment aja di issue ini
